baseurl = "https://hallettlab.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Hallett Lab"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
paginate = 12

[Params]
  subtitle = "Restoration and community ecology"
#  logo = "img/avatar-icon.png"
  favicon = "img/flower_2Xt_icon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/kc with cow.jpg"
  desc = "Serpentine grassland at Kirby Canyon"
  
[[Params.bigimg]]
  src = "img/shootingstar_cropped.jpg"
  desc = "Shooting star at Vasco Caves"
  
[[Params.bigimg]]
  src = "img/lianavish.jpg"
  desc = "Counting plants at Sierra Foothills"
  

  
#  # position: see values of CSS background-position.
#  position = "center top"

[Author]
  name = "Lauren Hallett"
  website = "hallettlab.github.io"
  email = "hallett@uoregon.edu"
  github = "laurenmh"
#  gitlab = "hallettlab"
  twitter = "lmhallett"


 [[menu.main]]
    identifier = "People"
    name = "People"
    weight = 2

[[menu.main]]
    parent = "People"
    name = "Current"
    url = "/lab member/"
    weight = 1
    
[[menu.main]]
    parent = "People"
    name = "Alumni"
    url = "/past lab member/"
    weight = 2
    
[[menu.main]]
    identifier = "Research"
    name = "Research"
    weight = 2

[[menu.main]]
    parent = "Research"
    name = "Where we work"
    url = "/study system/"
    weight = 1

[[menu.main]]
    parent = "Research"
    name = "What we do"
    url = "/research theme/"
    weight = 2


[[menu.main]]
    name = "Teaching"
    url = "teaching"
    weight = 3
 
    
 [[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 4
    
    [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 5
    
  [[menu.main]]
    name = "Contact"
    url = "contact"
    weight = 5
    
        
#  [[menu.main]]
#    name = "Hiring!"
#    url = "hiring"
#    weight = 6
    
    
#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3
    
  
